### ISSUE TITLE
Download All for one device?

### ISSUE THREAD

**Issue by joerican** [davglass/doorbot#46]
I have been trying to modify the download-all example to just pick one device based on ID but I can seem to get it to work. Would it too hard to show an example of how to download all from just one device ?

**Comment by piejanssens** [comment]
Same here, download all is not working for me. I need to go back further in time and the ring.com UI doesn't let me do it without scrolling for a couple of days.
After a few files it suddenly stops with an error.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at /Users/xx/doorbot/examples/download-all.js:65:46
    at /Users/xx/node_modules/doorbot/doorbot.js:357:13
    at /Users/xx/node_modules/doorbot/doorbot.js:176:17
```
